import '../models/quote.dart';

final List<String> categories = [
  "Motivational",
  "Inspirational",
  "Life",
  "Wisdom",
  "Historical",
  "Literary",
  "Philosophy",
  "Success",
];

List<Quote> quotesList = [
  Quote(
    text:
        "The only limit to our realization of tomorrow is our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "Motivational",
    details:
        "Franklin D. Roosevelt was the 32nd President of the United States.",
    source: "HistoricalQuotes",
  ),
  Quote(
    text: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    category: "Inspirational",
    details: "Theodore Roosevelt was the 26th President of the United States.",
    source: "HistoricalQuotes",
  ),
  Quote(
    text: "Life is short. Live passionately.",
    author: "Unknown",
    category: "Life",
    details: "A concise reminder about living life to the fullest",
    source: "WisdomQuotes",
  ),
  Quote(
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Success",
    details: "Steve Jobs was the co-founder of Apple Inc.",
    source: "WisdomQuotes",
  ),
  Quote(
    text: "The future is shaped by your dreams.",
    author: "InspirobotAI",
    category: "Inspirational",
    details: "Generated by artificial intelligence for modern inspiration",
    source: "Inspirobot",
  ),
  Quote(
    text:
        "In nature's realm, find peace sublime, Where wisdom flows through space and time.",
    author: "Sarah Mitchell",
    category: "Literary",
    details: "Contemporary poet featured on Art of Poets",
    source: "Art of Poets",
  ),
  Quote(
    text: "On this day in 1969, Apollo 11 landed on the moon.",
    author: "Historical Record",
    category: "Historical",
    details: "One of humanity's greatest achievements",
    source: "Britannica",
  ),
  // Add more quotes as needed
  // Inspiration
  Quote(
    text: "Life is short. Live passionately.",
    author: "Bjorn Borg",
    category: "Inspiration",
    source: "WisdomQuotes",
    details:
        "Bjorn Borg is a Swedish former world No. 1 tennis player widely considered to be one of the greatest players in tennis history.",
  ),
  Quote(
    text: "Dream big. Start small. Act now.",
    author: "Robin Sharma",
    category: "Inspiration",
    source: "WisdomQuotes",
    details:
        "Robin Sharma is a Canadian writer and leadership speaker, best known for his The Monk Who Sold His Ferrari book series.",
  ),
  Quote(
    text: "Every moment is a fresh beginning.",
    author: "T.S. Eliot",
    category: "Inspiration",
    source: "Art of Poets",
    details:
        "T.S. Eliot was a poet, essayist, publisher, playwright, and literary critic. He received the Nobel Prize in Literature in 1948.",
  ),
  Quote(
    text: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    category: "Inspiration",
    source: "WisdomQuotes",
    details:
        "Oprah Winfrey is an American talk show host, actress, producer, and philanthropist, best known for her talk show, The Oprah Winfrey Show.",
  ),
  Quote(
    text: "Make each day your masterpiece.",
    author: "John Wooden",
    category: "Inspiration",
    source: "WisdomQuotes",
    details:
        "John Wooden was an American basketball coach and player who won ten NCAA national championships in a 12-year period as head coach at UCLA.",
  ),

  // Wisdom
  Quote(
    text: "Knowledge speaks, but wisdom listens.",
    author: "Jimi Hendrix",
    category: "Wisdom",
    source: "WisdomQuotes",
    details:
        "Jimi Hendrix was an American musician, singer, and songwriter, widely regarded as one of the most influential electric guitarists in history.",
  ),
  Quote(
    text: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "Wisdom",
    source: "Britannica",
    details:
        "Socrates was a Greek philosopher from Athens who is credited as the founder of Western philosophy and among the first moral philosophers.",
  ),
  Quote(
    text: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    category: "Wisdom",
    source: "WisdomQuotes",
    details:
        "Leonardo da Vinci was an Italian polymath of the Renaissance whose areas of interest included invention, drawing, painting, sculpture, architecture, science, and engineering.",
  ),
  Quote(
    text: "To know thyself is the beginning of wisdom.",
    author: "Aristotle",
    category: "Wisdom",
    source: "Britannica",
    details:
        "Aristotle was a Greek philosopher and scientist who is considered one of the greatest intellectual figures of Western history.",
  ),
  Quote(
    text: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    category: "Wisdom",
    source: "WisdomQuotes",
    details:
        "Socrates was one of the founders of Western philosophical thought, known for his method of elenchos, or questioning to test ideas and assumptions.",
  ),

  // Motivation
  Quote(
    text: "Done is better than perfect.",
    author: "Sheryl Sandberg",
    category: "Motivation",
    source: "WisdomQuotes",
    details:
        "Sheryl Sandberg is an American business executive, serving as the chief operating officer of Meta Platforms and founder of LeanIn.Org.",
  ),
  Quote(
    text: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
    category: "Motivation",
    source: "Art of Poets",
    details:
        "Pablo Picasso was a Spanish painter, sculptor, printmaker, and ceramicist who revolutionized modern art in the 20th century.",
  ),
  Quote(
    text: "Quality is not an act, it is a habit.",
    author: "Aristotle",
    category: "Motivation",
    source: "Britannica",
    details:
        "Aristotle was a Greek philosopher who made significant contributions to logic, metaphysics, mathematics, physics, biology, botany, ethics, politics, agriculture, medicine, dance, and theatre.",
  ),
  Quote(
    text: "Focus on the step in front of you, not the whole staircase.",
    author: "Martin Luther King Jr.",
    category: "Motivation",
    source: "WisdomQuotes",
    details:
        "Martin Luther King Jr. was an American Baptist minister and activist who became the most visible spokesperson and leader in the civil rights movement.",
  ),
  Quote(
    text: "The future depends on what you do today.",
    author: "Mahatma Gandhi",
    category: "Motivation",
    source: "WisdomQuotes",
    details:
        "Mahatma Gandhi was an Indian lawyer, anti-colonial nationalist and political ethicist who employed nonviolent resistance to lead India's successful campaign for independence.",
  ),
  Quote(
    text:
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Motivational",
    source: "WisdomQuotes",
    details:
        "Winston Churchill was Prime Minister of the United Kingdom during World War II and led Britain to victory.",
  ),
  Quote(
    text:
        "The only way to achieve the impossible is to believe it is possible.",
    author: "Charles Kingsleigh",
    category: "Motivational",
    source: "Literary",
    details:
        "A memorable quote that emphasizes the power of belief and determination.",
  ),
  Quote(
    text: "Your time is limited, don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "Motivational",
    source: "WisdomQuotes",
    details:
        "Steve Jobs was the co-founder of Apple Inc. and a pioneer of the personal computer revolution.",
  ),

  // Life
  Quote(
    text: "Life is what happens while you're busy making other plans.",
    author: "John Lennon",
    category: "Life",
    source: "WisdomQuotes",
    details:
        "John Lennon was an English singer, songwriter, musician and peace activist who achieved worldwide fame as the founder, co-songwriter, co-lead vocalist and rhythm guitarist of the Beatles.",
  ),
  Quote(
    text: "Life shrinks or expands in proportion to one's courage.",
    author: "Anaïs Nin",
    category: "Life",
    source: "Art of Poets",
    details:
        "Anaïs Nin was a French-Cuban American diarist, essayist, novelist, and writer of short stories and erotica. Her journals span more than 60 years.",
  ),
  Quote(
    text: "The purpose of life is a life of purpose.",
    author: "Robert Byrne",
    category: "Life",
    source: "WisdomQuotes",
    details:
        "Robert Byrne was an American author and Billiards player who wrote several books on various subjects including pool, chess, and writing.",
  ),
  Quote(
    text: "Life is really simple, but we insist on making it complicated.",
    author: "Confucius",
    category: "Life",
    source: "Britannica",
    details:
        "Confucius was a Chinese philosopher and politician of the Spring and Autumn period who was traditionally considered the paragon of Chinese sages.",
  ),
  Quote(
    text: "Life is short, art is long.",
    author: "Hippocrates",
    category: "Life",
    source: "Britannica",
    details:
        "Hippocrates was a Greek physician of the Classical period who is considered one of the most outstanding figures in the history of medicine.",
  ),

  // Philosophy
  Quote(
    text: "I think, therefore I am.",
    author: "René Descartes",
    category: "Philosophy",
    source: "Britannica",
    details:
        "René Descartes was a French philosopher, mathematician, and scientist. Often called the father of modern Western philosophy, he laid the foundation for rationalism.",
  ),
  Quote(
    text: "He who has a why to live can bear almost any how.",
    author: "Friedrich Nietzsche",
    category: "Philosophy",
    source: "WisdomQuotes",
    details:
        "Friedrich Nietzsche was a German philosopher, cultural critic, and philologist whose work has exerted a profound influence on modern philosophy.",
  ),
  Quote(
    text:
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Aristotle",
    category: "Philosophy",
    source: "Britannica",
    details:
        "Aristotle was one of the greatest philosophers who ever lived and the first genuine scientist in history. He made pioneering contributions to all fields of philosophy and science.",
  ),
  Quote(
    text: "The only thing I know is that I know nothing.",
    author: "Socrates",
    category: "Philosophy",
    source: "WisdomQuotes",
    details:
        "Socrates was a classical Greek philosopher credited as one of the founders of Western philosophy. His way of examination and questioning is known as the Socratic method.",
  ),
  Quote(
    text:
        "Happiness is not something ready-made. It comes from your own actions.",
    author: "Dalai Lama",
    category: "Philosophy",
    source: "WisdomQuotes",
    details:
        "The Dalai Lama is the spiritual leader of Tibetan Buddhism and advocates for the welfare of Tibetans. He has received numerous awards, including the Nobel Peace Prize.",
  ),
  Quote(
    text: "Man is condemned to be free.",
    author: "Jean-Paul Sartre",
    category: "Philosophy",
    source: "Britannica",
    details:
        "Jean-Paul Sartre was a French philosopher, playwright, novelist, and political activist, a pioneer of existentialism who emphasized individual existence, freedom and choice.",
  ),

  // Additional Historical Quotes
  Quote(
    text: "Those who don't know history are destined to repeat it.",
    author: "Edmund Burke",
    category: "Historical",
    source: "Britannica",
    details:
        "Edmund Burke was an Irish statesman and political theorist who served in British Parliament.",
  ),
  Quote(
    text: "History will be kind to me for I intend to write it.",
    author: "Winston Churchill",
    category: "Historical",
    source: "Britannica",
    details:
        "Churchill was not only a statesman but also won the Nobel Prize in Literature.",
  ),
  Quote(
    text: "The more you know of your history, the more liberated you are.",
    author: "Maya Angelou",
    category: "Historical",
    source: "WisdomQuotes",
    details:
        "Maya Angelou was an American poet, memoirist, and civil rights activist.",
  ),

  // Additional Literary Quotes
  Quote(
    text: "To be, or not to be, that is the question.",
    author: "William Shakespeare",
    category: "Literary",
    source: "Art of Poets",
    details:
        "From Hamlet, one of Shakespeare's most famous plays. Shakespeare was an English playwright and poet.",
  ),
  Quote(
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    category: "Literary",
    source: "Art of Poets",
    details:
        "J.R.R. Tolkien was an English writer, poet, and philologist, best known for The Lord of the Rings.",
  ),
  Quote(
    text: "It was the best of times, it was the worst of times.",
    author: "Charles Dickens",
    category: "Literary",
    source: "Art of Poets",
    details:
        "Opening line from A Tale of Two Cities. Dickens was a renowned English novelist.",
  ),

  // Additional Success Quotes
  Quote(
    text:
        "Success usually comes to those who are too busy to be looking for it.",
    author: "Henry David Thoreau",
    category: "Success",
    source: "WisdomQuotes",
    details: "Thoreau was an American naturalist, essayist, and philosopher.",
  ),
  Quote(
    text:
        "Success is not the key to happiness. Happiness is the key to success.",
    author: "Albert Schweitzer",
    category: "Success",
    source: "WisdomQuotes",
    details:
        "Schweitzer was a theologian, organist, writer, humanitarian, philosopher, and physician.",
  ),
  Quote(
    text:
        "The road to success and the road to failure are almost exactly the same.",
    author: "Colin R. Davis",
    category: "Success",
    source: "WisdomQuotes",
    details:
        "Sir Colin Davis was a renowned English conductor known for his interpretations of Mozart, Berlioz, and Sibelius.",
  ),
  Quote(
    text:
        "Success is walking from failure to failure with no loss of enthusiasm.",
    author: "Winston Churchill",
    category: "Success",
    source: "WisdomQuotes",
    details:
        "Churchill's determination and resilience helped lead Britain through WWII.",
  ),
];

// Helper function to get quotes by category
List<Quote> getQuotesByCategory(String category) {
  return quotesList.where((quote) => quote.category == category).toList();
}

// Helper function to get quotes by source
List<Quote> getQuotesBySource(String source) {
  return quotesList.where((quote) => quote.source == source).toList();
}
